Travis has been failing for ruby 1.9.3 with an error which says NoMethodError: undefined method 'spec' for Nil:NillClass It appears this is to do with the version of Bundler used by travis on 1.9.3 Thoughbot had a commit which worked around it for them and I am trying it out line by line because I don't really understand all that is in travis.
The Thoughbot commit can be found here:
https://github.com/thoughtbot/factory_girl/commit/3c0547fa508d212f79050301d5622434e4731c48